spring:
  datasource:
    url: jdbc:mysql://quanlidoibong-1-quanlidoibong-1.b.aivencloud.com:18183/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_jjxxfT7utF_LbStoOlY
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
